apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
