apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: localhost:5000/order-service:latest
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: order-config
