apiVersion: v1
kind: Service
metadata:
  name: order-service-blue
  namespace: ecommerce
spec:
  selector:
    app: order
    version: blue   # Change this to "blue" or "green" based on routing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
