apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce
spec:
  selector:
    app: product
    version: green   # Change to "blue" or "green" as needed
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
