apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-green
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
      version: green
  template:
    metadata:
      labels:
        app: product
        version: green
    spec:
      containers:
      - name: product
        image: yasir1510/product:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
